//
// Copyright (c) Microsoft Corporation. All rights reserved.
//
// DO NOT HAND-EDIT THIS FILE.
//
// This file was generated by setup_public_headers.py script.
// Any changes made to this file will be overwritten.

/**
 * @file _att_cfg.h
 *
 * @brief Configuration and common macros for SDK code.
 * Do not include this file directly.
 *
 * @note You MUST NOT use any symbols (macros, functions, structures, enums, etc.)
 * prefixed with an underscore ('_') directly in your application code. These symbols
 * are part of the SDK's internal implementation; we do not document these symbols
 * and they are subject to change in future versions of the SDK which would break your code.
 */

#ifndef _ATT_CFG_H
#define _ATT_CFG_H

/**
 * @brief Inline function.
 */
#ifdef _MSC_VER
#define ATT_INLINE static __forceinline
#elif defined(__GNUC__) || defined(__clang__) // !_MSC_VER
#define ATT_INLINE __attribute__((always_inline)) static inline
#else // !_MSC_VER !__GNUC__ !__clang__
#define ATT_INLINE static inline
#endif // _MSC_VER

/**
 * @brief Enforce that the return value is handled (only applicable on supported compilers).
 */
#ifdef _MSC_VER
#define ATT_NODISCARD _Check_return_
#elif defined(__GNUC__) || defined(__clang__) // !_MSC_VER
#define ATT_NODISCARD __attribute__((warn_unused_result))
#else // !_MSC_VER !__GNUC__ !__clang__
#define ATT_NODISCARD
#endif // _MSC_VER

#endif // _ATT_CFG_H
